//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAYCANHNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string detail { get; set; }
    }
}
