//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAYCANHNT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKIN
    {
        public int id { get; set; }
        public string logo { get; set; }
        public string comercial { get; set; }
        public string comercial_link { get; set; }
        public string googlemap { get; set; }
        public string fanpage { get; set; }
        public string footer { get; set; }
        public string youtube { get; set; }
        public string aboutus { get; set; }
        public string shopinfo { get; set; }
        public string deliveryinfo { get; set; }
    }
}
