//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CART()
        {
            this.CART_DETAIL = new HashSet<CART_DETAIL>();
        }
    
        public int ID_CART { get; set; }
        public Nullable<System.DateTime> DATEBEGIN { get; set; }
        public string META { get; set; }
        public Nullable<int> ORDER { get; set; }
        public string LINK { get; set; }
        public Nullable<int> HIDE { get; set; }
        public Nullable<int> ID_USERS { get; set; }
    
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CART_DETAIL> CART_DETAIL { get; set; }
    }
}
